CREATE TABLE IF NOT EXISTS categories (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (id, name, active)
SELECT DISTINCT
    category_id,
    CASE WHEN category_id = 1 THEN 'Geral' ELSE 'Categoria ' || category_id END,
    TRUE
FROM products
WHERE category_id > 0
ON CONFLICT (id) DO NOTHING;

INSERT INTO categories (id, name, active)
VALUES (1, 'Geral', TRUE)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('categories', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM categories), 1), 1),
    TRUE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'products'::regclass
          AND conname = 'fk_products_category'
    ) THEN
        ALTER TABLE products
            ADD CONSTRAINT fk_products_category
            FOREIGN KEY (category_id) REFERENCES categories(id)
            ON DELETE RESTRICT NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_categories_active ON categories (active, id);
