CREATE TABLE IF NOT EXISTS orders (
    id                 SERIAL PRIMARY KEY,
    user_id            INTEGER NOT NULL,
    total              NUMERIC(10, 2) NOT NULL,
    status             VARCHAR(50) NOT NULL DEFAULT 'pending',
    external_reference VARCHAR(255) NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_items (
    id         SERIAL PRIMARY KEY,
    order_id   INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity   INTEGER NOT NULL DEFAULT 1,
    price      NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id             SERIAL PRIMARY KEY,
    order_id       INTEGER NOT NULL,
    payment_method VARCHAR(50),
    payment_status VARCHAR(50) DEFAULT 'pending',
    transaction_id VARCHAR(255),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_payments_transaction ON payments(transaction_id);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS reference VARCHAR(64);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128);

UPDATE orders
SET reference = 'ORD-LEGACY-' || id
WHERE reference IS NULL OR BTRIM(reference) = '';

ALTER TABLE orders ALTER COLUMN reference SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_reference ON orders(reference);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_buyer_idempotency_key
    ON orders(user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_buyer_created_at ON orders(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS stock_reservations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER NOT NULL,
    product_id  INTEGER NOT NULL,
    quantity    INTEGER NOT NULL,
    status      VARCHAR(16) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP NULL,
    CONSTRAINT fk_stock_reservations_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_reservations_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservations_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_stock_reservations_status
        CHECK (status IN ('reserved', 'consumed', 'released')),
    CONSTRAINT chk_stock_reservations_release_timestamp
        CHECK ((status = 'released' AND released_at IS NOT NULL)
            OR (status <> 'released' AND released_at IS NULL)),
    CONSTRAINT uq_stock_reservations_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_stock_reservations_order_status
    ON stock_reservations(order_id, status);
